### ISSUE TITLE
Kubeflow on GCP - 1.2.0 release tracker

### ISSUE THREAD

**Issue by Bobgy** [kubeflow/gcp-blueprints#139]
Creating an issue to track efforts required before 1.2.0 release.

EDIT: upstream Kubeflow 1.2 release issue: https://github.com/kubeflow/kubeflow/issues/5371

TODOs:
* [x] P0 https://github.com/kubeflow/gcp-blueprints/issues/143
* [x] P0 Update KFP to 1.0.4
* [x] P0 https://github.com/kubeflow/gcp-blueprints/pull/169
* [x] Upgrade config connector to latest https://github.com/kubeflow/manifests/pull/1595
* [x] P0 https://github.com/kubeflow/gcp-blueprints/issues/145
* [x] P0 https://github.com/kubeflow/gcp-blueprints/issues/142 we need documentation
* [x] P1 Adopt config connector GKE add-on or operator installation: https://github.com/kubeflow/gcp-blueprints/issues/148
* [x] P1 https://github.com/kubeflow/gcp-blueprints/issues/149
* [x] P1 https://github.com/kubeflow/gcp-blueprints/issues/160
* [x] P1 kubeflow/gcp-blueprints#155
* [x] P1 usability: tell troubleshooting instructions when GCP resources timed out https://github.com/kubeflow/gcp-blueprints/pull/171, validate characters in name https://github.com/kubeflow/gcp-blueprints/pull/170
* [x] P1 https://github.com/kubeflow/gcp-blueprints/pull/173

Out of scope
* [ ] P2 https://github.com/kubeflow/gcp-blueprints/issues/158 (there's a blocker)
* [ ] P2 https://github.com/kubeflow/gcp-blueprints/issues/144
* [ ] P2 https://github.com/kubeflow/pipelines/issues/4356
* [ ] P2 https://github.com/GoogleCloudPlatform/k8s-config-connector/issues/259#issuecomment-681145805 change nodeConfig to separate nodePool

**Comment by subodh101** [comment]
[Website doc updates] Update setting the values step: https://github.com/kubeflow/website/pull/2126

**Comment by Bobgy** [comment]
Renamed to 1.2.0 release tracker, because we are close to Kubeflow 1.2 release.

**Comment by Bobgy** [comment]
https://github.com/kubeflow/gcp-blueprints/pull/169 is the last PR we need to get in. After that, I believe we can cut v1.2.0 release once the manifest repo pins a version.

**Comment by Bobgy** [comment]
Logging some errors when trying to upgrade from Kubeflow v1.1:
1. 
> Resource: "apps/v1, Resource=statefulsets", GroupVersionKind: "apps/v1, Kind=StatefulSet"
Name: "kfserving-controller-manager", Namespace: "kubeflow"
for: ".build/kubeflow-apps/apps_v1_statefulset_kfserving-controller-manager.yaml": StatefulSet.apps "kfserving-controller-manager" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', and 'updateStrategy' are forbidden

workaround: `k delete statefulset kfserving-controller-manager -n kubeflow --wait`

**Comment by Bobgy** [comment]
2.
> {"metadata":{"annotations":{"kubectl.kubernetes.io/last-applied-configuration":"{\"apiVersion\":\"apiextensions.k8s.io/v1beta1\",\"kind\":\"CustomResourceDefinition\",\"metadata\":{\"annotations\":{},\"labels\":{\"app.kubernetes.io/component\":\"katib\",\"app.kubernetes.io/name\":\"katib-crds\"},\"name\":\"experiments.kubeflow.org\"},\"spec\":{\"additionalPrinterColumns\":[{\"JSONPath\":\".status.conditions[-1:].type\",\"name\":\"Type\",\"type\":\"string\"},{\"JSONPath\":\".status.conditions[-1:].status\",\"name\":\"Status\",\"type\":\"string\"},{\"JSONPath\":\".metadata.creationTimestamp\",\"name\":\"Age\",\"type\":\"date\"}],\"group\":\"kubeflow.org\",\"names\":{\"categories\":[\"all\",\"kubeflow\",\"katib\"],\"kind\":\"Experiment\",\"plural\":\"experiments\",\"singular\":\"experiment\"},\"scope\":\"Namespaced\",\"subresources\":{\"status\":{}},\"version\":\"v1beta1\"}}\n"}},"spec":{"additionalPrinterColumns":[{"JSONPath":".status.conditions[-1:].type","name":"Type","type":"string"},{"JSONPath":".status.conditions[-1:].status","name":"Status","type":"string"},{"JSONPath":".metadata.creationTimestamp","name":"Age","type":"date"}],"version":"v1beta1"}}
to:
Resource: "apiextensions.k8s.io/v1beta1, Resource=customresourcedefinitions", GroupVersionKind: "apiextensions.k8s.io/v1beta1, Kind=CustomResourceDefinition"
Name: "experiments.kubeflow.org", Namespace: ""
for: ".build/kubeflow-apps/apiextensions.k8s.io_v1beta1_customresourcedefinition_experiments.kubeflow.org.yaml": CustomResourceDefinition.apiextensions.k8s.io "experiments.kubeflow.org" is invalid: spec.version: Invalid value: "v1beta1": must match the first version in spec.versions
Error from server (Invalid): error when applying patch:
{"metadata":{"annotations":{"kubectl.kubernetes.io/last-applied-configuration":"{\"apiVersion\":\"apiextensions.k8s.io/v1beta1\",\"kind\":\"CustomResourceDefinition\",\"metadata\":{\"annotations\":{},\"labels\":{\"app.kubernetes.io/component\":\"katib\",\"app.kubernetes.io/name\":\"katib-crds\"},\"name\":\"suggestions.kubeflow.org\"},\"spec\":{\"additionalPrinterColumns\":[{\"JSONPath\":\".status.conditions[-1:].type\",\"name\":\"Type\",\"type\":\"string\"},{\"JSONPath\":\".status.conditions[-1:].status\",\"name\":\"Status\",\"type\":\"string\"},{\"JSONPath\":\".spec.requests\",\"name\":\"Requested\",\"type\":\"string\"},{\"JSONPath\":\".status.suggestionCount\",\"name\":\"Assigned\",\"type\":\"string\"},{\"JSONPath\":\".metadata.creationTimestamp\",\"name\":\"Age\",\"type\":\"date\"}],\"group\":\"kubeflow.org\",\"names\":{\"categories\":[\"all\",\"kubeflow\",\"katib\"],\"kind\":\"Suggestion\",\"plural\":\"suggestions\",\"singular\":\"suggestion\"},\"scope\":\"Namespaced\",\"subresources\":{\"status\":{}},\"version\":\"v1beta1\"}}\n"}},"spec":{"version":"v1beta1"}}
to:
Resource: "apiextensions.k8s.io/v1beta1, Resource=customresourcedefinitions", GroupVersionKind: "apiextensions.k8s.io/v1beta1, Kind=CustomResourceDefinition"
Name: "suggestions.kubeflow.org", Namespace: ""
for: ".build/kubeflow-apps/apiextensions.k8s.io_v1beta1_customresourcedefinition_suggestions.kubeflow.org.yaml": CustomResourceDefinition.apiextensions.k8s.io "suggestions.kubeflow.org" is invalid: spec.version: Invalid value: "v1beta1": must match the first version in spec.versions
Error from server (Invalid): error when applying patch:
{"metadata":{"annotations":{"kubectl.kubernetes.io/last-applied-configuration":"{\"apiVersion\":\"apiextensions.k8s.io/v1beta1\",\"kind\":\"CustomResourceDefinition\",\"metadata\":{\"annotations\":{},\"labels\":{\"app.kubernetes.io/component\":\"katib\",\"app.kubernetes.io/name\":\"katib-crds\"},\"name\":\"trials.kubeflow.org\"},\"spec\":{\"additionalPrinterColumns\":[{\"JSONPath\":\".status.conditions[-1:].type\",\"name\":\"Type\",\"type\":\"string\"},{\"JSONPath\":\".status.conditions[-1:].status\",\"name\":\"Status\",\"type\":\"string\"},{\"JSONPath\":\".metadata.creationTimestamp\",\"name\":\"Age\",\"type\":\"date\"}],\"group\":\"kubeflow.org\",\"names\":{\"categories\":[\"all\",\"kubeflow\",\"katib\"],\"kind\":\"Trial\",\"plural\":\"trials\",\"singular\":\"trial\"},\"scope\":\"Namespaced\",\"subresources\":{\"status\":{}},\"version\":\"v1beta1\"}}\n"}},"spec":{"version":"v1beta1"}}
to:
Resource: "apiextensions.k8s.io/v1beta1, Resource=customresourcedefinitions", GroupVersionKind: "apiextensions.k8s.io/v1beta1, Kind=CustomResourceDefinition"
Name: "trials.kubeflow.org", Namespace: ""
for: ".build/kubeflow-apps/apiextensions.k8s.io_v1beta1_customresourcedefinition_trials.kubeflow.org.yaml": CustomResourceDefinition.apiextensions.k8s.io "trials.kubeflow.org" is invalid: spec.version: Invalid value: "v1beta1": must match the first version in spec.versions

**Comment by Bobgy** [comment]
OK, apply all succeeded.
I also saw katib controller was in crashloopbackoff, because of the CRD version problem.
But after a restart, it run successfully now.

**Comment by subodh101** [comment]
Can we add the following with `kubectl delete` for `statefulset/kfserving-controller-manager crds/experiments.kubeflow.org ...`

```
--ignore-not-found=false: Treat "resource not found" as a successful delete.
```

with kubeflow cluster context before applying those specific resources?

**Comment by Bobgy** [comment]
Because deleting CRDs delete all user custom resources, I think it's best to document that and ask users to do that.

Also, this will be one off upgrade requirement

**Comment by Bobgy** [comment]
OK, everything's ready. I'll update documentation and pin a release

**Comment by Bobgy** [comment]
Pinned v1.2.0: https://github.com/kubeflow/gcp-blueprints/commit/db08b1682c8758cfb35e6d7faee9e7d87ae6fe26
working on documentation updates:
- [ ] https://github.com/kubeflow/website/pull/2370

I also need to write upgrade instructions for kubeflow cluster.

**Comment by Bobgy** [comment]
Done

**Comment by Jboulery** [comment]
> > {"metadata":{"annotations":{"kubectl.kubernetes.io/last-applied-configuration":"{"apiVersion":"apiextensions.k8s.io/v1beta1","kind":"CustomResourceDefinition","metadata":{"annotations":{},"labels":{"app.kubernetes.io/component":"katib","app.kubernetes.io/name":"katib-crds"},"name":"experiments.kubeflow.org"},"spec":{"additionalPrinterColumns":[{"JSONPath":".status.conditions[-1:].type","name":"Type","type":"string"},{"JSONPath":".status.conditions[-1:].status","name":"Status","type":"string"},{"JSONPath":".metadata.creationTimestamp","name":"Age","type":"date"}],"group":"kubeflow.org","names":{"categories":["all","kubeflow","katib"],"kind":"Experiment","plural":"experiments","singular":"experiment"},"scope":"Namespaced","subresources":{"status":{}},"version":"v1beta1"}}\n"}},"spec":{"additionalPrinterColumns":[{"JSONPath":".status.conditions[-1:].type","name":"Type","type":"string"},{"JSONPath":".status.conditions[-1:].status","name":"Status","type":"string"},{"JSONPath":".metadata.creationTimestamp","name":"Age","type":"date"}],"version":"v1beta1"}}
> > to:
> > Resource: "apiextensions.k8s.io/v1beta1, Resource=customresourcedefinitions", GroupVersionKind: "apiextensions.k8s.io/v1beta1, Kind=CustomResourceDefinition"
> > Name: "experiments.kubeflow.org", Namespace: ""
> > for: ".build/kubeflow-apps/apiextensions.k8s.io_v1beta1_customresourcedefinition_experiments.kubeflow.org.yaml": CustomResourceDefinition.apiextensions.k8s.io "experiments.kubeflow.org" is invalid: spec.version: Invalid value: "v1beta1": must match the first version in spec.versions
> 
> > Error from server (Invalid): error when applying patch:
> > {"metadata":{"annotations":{"kubectl.kubernetes.io/last-applied-configuration":"{"apiVersion":"apiextensions.k8s.io/v1beta1","kind":"CustomResourceDefinition","metadata":{"annotations":{},"labels":{"app.kubernetes.io/component":"katib","app.kubernetes.io/name":"katib-crds"},"name":"suggestions.kubeflow.org"},"spec":{"additionalPrinterColumns":[{"JSONPath":".status.conditions[-1:].type","name":"Type","type":"string"},{"JSONPath":".status.conditions[-1:].status","name":"Status","type":"string"},{"JSONPath":".spec.requests","name":"Requested","type":"string"},{"JSONPath":".status.suggestionCount","name":"Assigned","type":"string"},{"JSONPath":".metadata.creationTimestamp","name":"Age","type":"date"}],"group":"kubeflow.org","names":{"categories":["all","kubeflow","katib"],"kind":"Suggestion","plural":"suggestions","singular":"suggestion"},"scope":"Namespaced","subresources":{"status":{}},"version":"v1beta1"}}\n"}},"spec":{"version":"v1beta1"}}
> > to:
> > Resource: "apiextensions.k8s.io/v1beta1, Resource=customresourcedefinitions", GroupVersionKind: "apiextensions.k8s.io/v1beta1, Kind=CustomResourceDefinition"
> > Name: "suggestions.kubeflow.org", Namespace: ""
> > for: ".build/kubeflow-apps/apiextensions.k8s.io_v1beta1_customresourcedefinition_suggestions.kubeflow.org.yaml": CustomResourceDefinition.apiextensions.k8s.io "suggestions.kubeflow.org" is invalid: spec.version: Invalid value: "v1beta1": must match the first version in spec.versions
> 
> > Error from server (Invalid): error when applying patch:
> > {"metadata":{"annotations":{"kubectl.kubernetes.io/last-applied-configuration":"{"apiVersion":"apiextensions.k8s.io/v1beta1","kind":"CustomResourceDefinition","metadata":{"annotations":{},"labels":{"app.kubernetes.io/component":"katib","app.kubernetes.io/name":"katib-crds"},"name":"trials.kubeflow.org"},"spec":{"additionalPrinterColumns":[{"JSONPath":".status.conditions[-1:].type","name":"Type","type":"string"},{"JSONPath":".status.conditions[-1:].status","name":"Status","type":"string"},{"JSONPath":".metadata.creationTimestamp","name":"Age","type":"date"}],"group":"kubeflow.org","names":{"categories":["all","kubeflow","katib"],"kind":"Trial","plural":"trials","singular":"trial"},"scope":"Namespaced","subresources":{"status":{}},"version":"v1beta1"}}\n"}},"spec":{"version":"v1beta1"}}
> > to:
> > Resource: "apiextensions.k8s.io/v1beta1, Resource=customresourcedefinitions", GroupVersionKind: "apiextensions.k8s.io/v1beta1, Kind=CustomResourceDefinition"
> > Name: "trials.kubeflow.org", Namespace: ""
> > for: ".build/kubeflow-apps/apiextensions.k8s.io_v1beta1_customresourcedefinition_trials.kubeflow.org.yaml": CustomResourceDefinition.apiextensions.k8s.io "trials.kubeflow.org" is invalid: spec.version: Invalid value: "v1beta1": must match the first version in spec.versions
> 
> Workaround:
> `kubectl delete crds experiments.kubeflow.org suggestions.kubeflow.org trials.kubeflow.org`

Had the same problem with EKS and this workaround worked for me.
