### ISSUE TITLE
Kubeflow 1.4 Release Tracker

### ISSUE THREAD

**Issue by zijianjoy** [kubeflow/gcp-blueprints#301]
Pending:

- ~~Wait for https://github.com/kubeflow/manifests/pull/2033 to be merged.~~
- ~~Use kubeflow/manifests final 1.4 tag after release.~~
- ~~Make release candidate and final release for Google Cloud, needs to update tag version in document.~~

### P0:

- [x] https://github.com/kubeflow/pipelines/issues/5680 (2d)
- [x] #302
- [x] #308
- [x] https://github.com/kubeflow/gcp-blueprints/issues/298 (unknown) 
- [x] #304
- [x] #310
- [x] #324

### P1:
- [x] #306
- [x] #313
- [x] #315
- [x] #317
- [x] #309
- [ ] learn about pod_label 

### Optional:

- [x] #319
- [ ] #329
- [x] #320

**Comment by zijianjoy** [comment]
Track remaining items individually.
